-- Migration 022: Create email_templates table

CREATE TABLE email_templates (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID REFERENCES tenants(id),  -- NULL = default BRTNeura template
  template_type VARCHAR(50) NOT NULL,     -- welcome | registration_confirmation | payment_receipt | recovery_link | waitlist_confirmation | subscription_invoice | trial_expiring | subscription_cancelled
  subject VARCHAR(255) NOT NULL,
  html_body TEXT NOT NULL,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(tenant_id, template_type)
);

CREATE INDEX idx_email_templates_tenant ON email_templates(tenant_id);
CREATE INDEX idx_email_templates_type ON email_templates(template_type);

ALTER TABLE email_templates ENABLE ROW LEVEL SECURITY;

CREATE POLICY tenant_isolation_emails ON email_templates
  USING (tenant_id = (auth.jwt() ->> 'tenant_id')::UUID OR tenant_id IS NULL);

-- =============================================
-- Insert default BRTNeura email templates
-- =============================================

INSERT INTO email_templates (tenant_id, template_type, subject, html_body) VALUES

(NULL, 'welcome', 'Welcome to {{tenant_name}}!', '<!DOCTYPE html><html><head><meta charset="utf-8"><style>body{margin:0;padding:0;font-family:Arial,sans-serif;background:#f5f5f5}.container{max-width:600px;margin:0 auto;background:#fff}.header{background:{{primary_color}};color:#fff;padding:30px;text-align:center}.header img{max-height:50px;margin-bottom:10px}.body{padding:30px}.footer{padding:20px;text-align:center;color:#888;font-size:12px;background:#f9f9f9}</style></head><body><div class="container"><div class="header"><img src="{{tenant_logo_url}}" alt="{{tenant_name}}"><h1>Welcome!</h1></div><div class="body"><p>Hi {{attendee_name}},</p><p>Welcome to <strong>{{tenant_name}}</strong>. Your account has been created successfully.</p><p>You can now access your dashboard and manage your events.</p><p>If you have any questions, reach out to us at <a href="mailto:{{support_email}}">{{support_email}}</a>.</p></div><div class="footer"><p>{{tenant_name}} | <a href="mailto:{{support_email}}">{{support_email}}</a></p></div></div></body></html>'),

(NULL, 'registration_confirmation', 'Registration Confirmed - {{event_name}}', '<!DOCTYPE html><html><head><meta charset="utf-8"><style>body{margin:0;padding:0;font-family:Arial,sans-serif;background:#f5f5f5}.container{max-width:600px;margin:0 auto;background:#fff}.header{background:{{primary_color}};color:#fff;padding:30px;text-align:center}.header img{max-height:50px;margin-bottom:10px}.body{padding:30px}.details{background:#f9f9f9;border-radius:8px;padding:20px;margin:20px 0}.details table{width:100%}.details td{padding:8px 0;border-bottom:1px solid #eee}.details td:first-child{font-weight:bold;color:#555;width:40%}.footer{padding:20px;text-align:center;color:#888;font-size:12px;background:#f9f9f9}</style></head><body><div class="container"><div class="header"><img src="{{tenant_logo_url}}" alt="{{tenant_name}}"><h1>Registration Confirmed!</h1></div><div class="body"><p>Hi {{attendee_name}},</p><p>Your registration for <strong>{{event_name}}</strong> has been confirmed.</p><div class="details"><table><tr><td>Event</td><td>{{event_name}}</td></tr><tr><td>Date</td><td>{{event_date}}</td></tr><tr><td>Venue</td><td>{{event_venue}}</td></tr><tr><td>Pass Type</td><td>{{tier_name}}</td></tr><tr><td>Amount Paid</td><td>INR {{amount}}</td></tr><tr><td>Payment ID</td><td>{{payment_id}}</td></tr></table></div><p>We look forward to seeing you!</p></div><div class="footer"><p>{{tenant_name}} | <a href="mailto:{{support_email}}">{{support_email}}</a></p></div></div></body></html>'),

(NULL, 'payment_receipt', 'Payment Receipt - INR {{amount}}', '<!DOCTYPE html><html><head><meta charset="utf-8"><style>body{margin:0;padding:0;font-family:Arial,sans-serif;background:#f5f5f5}.container{max-width:600px;margin:0 auto;background:#fff}.header{background:{{primary_color}};color:#fff;padding:30px;text-align:center}.body{padding:30px}.receipt{border:2px solid {{primary_color}};border-radius:8px;padding:20px;margin:20px 0}.receipt h3{margin-top:0;color:{{primary_color}}}.receipt table{width:100%}.receipt td{padding:8px 0;border-bottom:1px solid #eee}.footer{padding:20px;text-align:center;color:#888;font-size:12px;background:#f9f9f9}</style></head><body><div class="container"><div class="header"><img src="{{tenant_logo_url}}" alt="{{tenant_name}}"><h1>Payment Receipt</h1></div><div class="body"><p>Hi {{attendee_name}},</p><p>Your payment has been confirmed.</p><div class="receipt"><h3>Receipt</h3><table><tr><td>Amount</td><td><strong>INR {{amount}}</strong></td></tr><tr><td>Payment ID</td><td>{{payment_id}}</td></tr><tr><td>Event</td><td>{{event_name}}</td></tr><tr><td>Pass Type</td><td>{{tier_name}}</td></tr></table></div></div><div class="footer"><p>{{tenant_name}} | <a href="mailto:{{support_email}}">{{support_email}}</a></p></div></div></body></html>'),

(NULL, 'recovery_link', 'Complete Your Registration - {{event_name}}', '<!DOCTYPE html><html><head><meta charset="utf-8"><style>body{margin:0;padding:0;font-family:Arial,sans-serif;background:#f5f5f5}.container{max-width:600px;margin:0 auto;background:#fff}.header{background:{{primary_color}};color:#fff;padding:30px;text-align:center}.body{padding:30px}.cta{display:inline-block;background:{{primary_color}};color:#fff;padding:14px 32px;border-radius:8px;text-decoration:none;font-weight:bold;margin:20px 0}.footer{padding:20px;text-align:center;color:#888;font-size:12px;background:#f9f9f9}</style></head><body><div class="container"><div class="header"><img src="{{tenant_logo_url}}" alt="{{tenant_name}}"><h1>Complete Your Registration</h1></div><div class="body"><p>Hi {{attendee_name}},</p><p>We noticed you started registering for <strong>{{event_name}}</strong> but didn''t complete payment.</p><p>Your {{tier_name}} spot is still reserved. Complete your registration now:</p><p style="text-align:center"><a href="{{recovery_link}}" class="cta">Complete Registration</a></p><p>If you have any trouble, contact us at <a href="mailto:{{support_email}}">{{support_email}}</a>.</p></div><div class="footer"><p>{{tenant_name}} | <a href="mailto:{{support_email}}">{{support_email}}</a></p></div></div></body></html>'),

(NULL, 'waitlist_confirmation', 'You''re on the Waitlist - {{event_name}}', '<!DOCTYPE html><html><head><meta charset="utf-8"><style>body{margin:0;padding:0;font-family:Arial,sans-serif;background:#f5f5f5}.container{max-width:600px;margin:0 auto;background:#fff}.header{background:{{primary_color}};color:#fff;padding:30px;text-align:center}.body{padding:30px}.footer{padding:20px;text-align:center;color:#888;font-size:12px;background:#f9f9f9}</style></head><body><div class="container"><div class="header"><img src="{{tenant_logo_url}}" alt="{{tenant_name}}"><h1>Waitlist Confirmed</h1></div><div class="body"><p>Hi {{attendee_name}},</p><p>You have been added to the waitlist for <strong>{{event_name}}</strong>.</p><p>We''ll notify you as soon as a spot opens up. Keep an eye on your email!</p></div><div class="footer"><p>{{tenant_name}} | <a href="mailto:{{support_email}}">{{support_email}}</a></p></div></div></body></html>'),

(NULL, 'subscription_invoice', 'Invoice for {{month}} - {{tenant_name}}', '<!DOCTYPE html><html><head><meta charset="utf-8"><style>body{margin:0;padding:0;font-family:Arial,sans-serif;background:#f5f5f5}.container{max-width:600px;margin:0 auto;background:#fff}.header{background:{{primary_color}};color:#fff;padding:30px;text-align:center}.body{padding:30px}.invoice{border:2px solid #ddd;border-radius:8px;padding:20px;margin:20px 0}.invoice table{width:100%}.invoice td{padding:8px 0;border-bottom:1px solid #eee}.footer{padding:20px;text-align:center;color:#888;font-size:12px;background:#f9f9f9}</style></head><body><div class="container"><div class="header"><h1>Monthly Invoice</h1></div><div class="body"><p>Hi,</p><p>Here is your invoice for <strong>{{month}}</strong>.</p><div class="invoice"><table><tr><td>Plan</td><td>{{tier_name}}</td></tr><tr><td>Amount</td><td><strong>INR {{amount}}</strong></td></tr><tr><td>Payment ID</td><td>{{payment_id}}</td></tr><tr><td>Period</td><td>{{month}}</td></tr></table></div></div><div class="footer"><p>BRTNeura Registration Platform</p></div></div></body></html>'),

(NULL, 'trial_expiring', 'Your Trial Ends in 3 Days', '<!DOCTYPE html><html><head><meta charset="utf-8"><style>body{margin:0;padding:0;font-family:Arial,sans-serif;background:#f5f5f5}.container{max-width:600px;margin:0 auto;background:#fff}.header{background:#f59e0b;color:#fff;padding:30px;text-align:center}.body{padding:30px}.cta{display:inline-block;background:#6366f1;color:#fff;padding:14px 32px;border-radius:8px;text-decoration:none;font-weight:bold;margin:20px 0}.footer{padding:20px;text-align:center;color:#888;font-size:12px;background:#f9f9f9}</style></head><body><div class="container"><div class="header"><h1>Trial Ending Soon</h1></div><div class="body"><p>Hi,</p><p>Your free trial of <strong>{{tenant_name}}</strong> ends in 3 days.</p><p>Upgrade now to keep all your features and data:</p><p style="text-align:center"><a href="{{registration_url}}" class="cta">Upgrade Now</a></p><p>After the trial ends, you will lose access to premium features.</p></div><div class="footer"><p>BRTNeura Registration Platform</p></div></div></body></html>'),

(NULL, 'subscription_cancelled', 'Subscription Cancelled - {{tenant_name}}', '<!DOCTYPE html><html><head><meta charset="utf-8"><style>body{margin:0;padding:0;font-family:Arial,sans-serif;background:#f5f5f5}.container{max-width:600px;margin:0 auto;background:#fff}.header{background:#ef4444;color:#fff;padding:30px;text-align:center}.body{padding:30px}.footer{padding:20px;text-align:center;color:#888;font-size:12px;background:#f9f9f9}</style></head><body><div class="container"><div class="header"><h1>Subscription Cancelled</h1></div><div class="body"><p>Hi,</p><p>Your subscription for <strong>{{tenant_name}}</strong> has been cancelled.</p><p>Your access will continue until the end of the current billing period.</p><p>If you change your mind, you can re-subscribe anytime from your dashboard.</p><p>We''d love to have you back!</p></div><div class="footer"><p>BRTNeura Registration Platform</p></div></div></body></html>');
